### PR TITLE
Add {DominoDataR}

### PR DESCRIPTION
**Pull request by datawookie**
1. Add `{DominoDataR}` as a dependency. At present installing from a forked copy of the repository which has been renamed to `DominoDataR` (the original version has hyphens in the repository name which appear to bork the dependency resolution).
2. Install the `dominodatalab-data` Python package. This is currently being done via `.onLoad()`, which is possibly not the most elegant solution. But it works. Also it makes package load a little noisy. We can suppress that noise once we are happy with how this works.

### CODE REVIEW

**Comment by daattali** [comment]
Thanks for the PR, but there's a couple issues

1. First of all, and this one's easy: The {reticulate} package needs to be defined in DESCRIPTION if it's being used

2. When this code runs in my workspace, I get a prompt that I have to manually deal with: 

    image

    Installing LCA should not require any manual input because otherwise it wouldn't be able to get installed automatically

3. Having it install in .onLoad is not good - all the dependencies need to be installed and ready to go when LCA is installed. It's poor user experience if they get onto a workspace, everything is installed, and when they try to use the tool it then starts installing something else.

Essentially this dominodatar package needs to be able to be available for use and all set up when LCA is installed.

**Comment by datawookie** [comment]
> Having it install in .onLoad is not good

Agreed. Do you have an alternative suggestion for installing the Python package during the install process?

**Comment by datawookie** [comment]
@daattali I've flung a bunch of time at this and don't see a way of installing either MiniConda or the Python packages during the installation of LCA. I've taken a look at a number of other packages that depend on `{reticulate}` and can't find any examples of how this is integrated into the package install.

How do you want this done?

I agree that having these things installed every time that the package is loaded is not optimal. However, if they are installed the first time that it's loaded, surely that would be okay? Alternatively, we do a lazy install when one of these packages is used. This would mean that as far as using the existing LCA functionality is concerned, nothing should change. But if you used the (new and yet to be implemented) functionality for loading data from Domino Data Sources then it would have to (automatically) install MiniConda and the Python dependencies.

**Comment by datawookie** [comment]
@daattali I've got this kind of working.

But I've been thinking, surely the installation of Python and the `dominodatalab-data` should probably happen in `DominoDataR`? If that's the case then I'll take these changes and create a PR on that repository instead.

**Comment by datawookie** [comment]
Hi @daattali, okay, this seems to do the trick. I'll clean up the commit history once you have signed off on the changes. The "Do you want to install MiniConda" thing is a known issue with the `{reticulate}` package and seems to appear on the first time that the package is used. In order to suppress this you can specify the path for the Python interpreter. I have started a list of places to look, starting with the location of the Conda Python on Domino. You might want to add the path for your platform to the list. I'm on Ubuntu and the default Python is in `/usr/bin/python`. Anyway, hope that you are satisfied with the revisions.

As mentioned above, I think that it would be good to move this into the `{DominoDataR}` package, but for the moment shall we do it here just so that we can move ahead with the functionality for loading from Domino Data Sources?

Thanks, Andrew.

**Comment by daattali** [comment]
> But I've been thinking, surely the installation of Python and the dominodatalab-data should probably happen in DominoDataR? If that's the case then I'll take these changes and create a PR on that repository instead.

Agreed! I commented on the other package's PR that I think a "Configure" file is what you were looking for rather than Makefile. I think/hope that'll take it to the finish line.

If that doesn't seem to work, then having a dedicated setup function that the user needs to call would be ok if it can do the installation automatically without any user input.

> is a known issue with the {reticulate} package 

If you can link to an actual github issue, I'd add my "ping" to that issue so that hopefully one day it'll be fixed :p

**Comment by datawookie** [comment]
@daattali this is the issue that I was referring to: https://github.com/rstudio/reticulate/issues/607. So it looks like this is "intended" behaviour, but something that we can work around by explicitly specifying the Python path.

**Comment by daattali** [comment]
solved via https://github.com/dominodatalab/DominoDataR/pull/4

**Pull request closed without merging**
